- name: Checkout Commit
  uses: actions/checkout@v3
  with:
    ref: ${{ env.GITHUB_SHA }}
- name: Get Head Commit Message
  id: get_head_commit_message
  run: echo "HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"
