
name: Notify on Pull Request

on:
  pull_request:
    branches: [master]


jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}
      - name: Get Commit Message
        run: |
          echo "::set-env name=COMMIT_MESSAGE::${{ github.event.head_commit.message }}"
      - name: Echo commit message
        run: echo "Commit SHA: ${{github.event.after}}, commit message: ${{env.COMMIT_MESSAGE}} (or ${COMMIT_MESSAGE})"
